services:
  web:
    image: ${DOCKER_REGISTRY-}linkedmink/road-wave-fm-web
    build:
      context: ./
      target: application
      # cache_from:
      #   - type=registry,ref=${DOCKER_REGISTRY-}linkedmink/road-wave-fm-web:build-cache
      # cache_to:
      #   - type=registry,ref=${DOCKER_REGISTRY-}linkedmink/road-wave-fm-web:build-cache,mode=max
      # platforms:
      #   - "linux/amd64"
      #   - "linux/arm64"
      tags:
        - "linkedmink/road-wave-fm-web:${PACKAGE_VERSION:-latest}"
    profiles:
      - deploy
    ports:
      - "127.0.0.1:80:80/tcp"
      - "127.0.0.1:443:443/tcp"
    volumes:
      - type: bind
        source: ./dist
        target: /usr/share/nginx/html
        read_only: true
      - type: bind
        source: ./config/nginx.conf
        target: /etc/nginx/http.d/default.conf
        read_only: true
      - type: bind
        source: ./config/localhost.secp384r1.crt
        target: /etc/ssl/certs/localhost.crt
        read_only: true
      - type: bind
        source: ./config/localhost.secp384r1.key
        target: /etc/ssl/certs/localhost.key
        read_only: true
    develop:
      watch:
        - action: rebuild
          path: src
        - action: rebuild
          path: package-lock.json

  web-watch:
    image: ${DOCKER_REGISTRY-}linkedmink/road-wave-fm-web:dev
    build:
      context: ./
      target: watch
      # cache_from:
      #   - type=registry,ref=${DOCKER_REGISTRY-}linkedmink/road-wave-fm-web:build-cache
      # cache_to:
      #   - type=registry,ref=${DOCKER_REGISTRY-}linkedmink/road-wave-fm-web:build-cache,mode=max
    profiles:
      - dev
    ports:
      - "127.0.0.1:8080:8080/tcp"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /home/node/app/src
        - action: rebuild
          path: package-lock.json
