services:
  web:
    image: linkedmink/road-wave-fm-web
    build:
      context: ./
      target: application
    profiles:
      - deploy
    ports:
      - "127.0.0.1:80:80/tcp"
      - "127.0.0.1:443:443/tcp"
    volumes:
      - type: bind
        source: ./dist
        target: /usr/share/nginx/html
        read_only: true
      - type: bind
        source: ./docker/nginx.conf
        target: /etc/nginx/http.d/default.conf
        read_only: true
      - type: bind
        source: ./docker/localhost.secp384r1.crt
        target: /etc/ssl/certs/localhost.crt
        read_only: true
      - type: bind
        source: ./docker/localhost.secp384r1.key
        target: /etc/ssl/certs/localhost.key
        read_only: true
    develop:
      watch:
        - action: rebuild
          path: src
        - action: rebuild
          path: package-lock.json

  web-watch:
    image: linkedmink/road-wave-fm-web:dev
    build:
      context: ./
      target: watch
    profiles:
      - dev
    ports:
      - "127.0.0.1:8080:8080/tcp"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /home/node/app/src
        - action: rebuild
          path: package-lock.json
