apiVersion: v1
kind: ConfigMap
metadata:
  name: road-wave-fm-web
data:
  config.json: |
  {
    "urls": {
      "user": "http://user.api.mydomain.local",
      "roadWave": "http://rwfm.api.mydomain.local"
    },
    "googleMapsApiKey": "<My Key>",
    "jwtPublicKey": "<My base64 key>",
    "logLevelConsole": 0,
    "logLevelPersist": 0
  }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: road-wave-fm-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: road-wave-fm-web
  template:
    metadata:
      labels:
        app: road-wave-fm-web
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: road-wave-fm-web
        image: linkedmink/road-wave-fm-web
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html/config.json
          subPath: config.json
          readonly: true
  volumes:
    - name: config-volume
      configMap:
        name: road-wave-fm-web

---
apiVersion: v1
kind: Service
metadata:
  name: road-wave-fm-web
spec:
  ports:
  - port: 80
  selector:
    app: road-wave-fm-web
