export enum FormatsActionType {
  SAVE = "FORMAT_SAVE",
  SELECT = "FORMAT_SELECT",
  SELECT_CONFIRM = "FORMAT_SELECT_CONFIRM",
  SELECT_CANCEL = "FORMAT_SELECT_CANCEL",
  RESTORE = "FORMAT_RESTORE",
}

export enum StationsActionType {
  STORE = "STATION_STORE",
  SELECT = "STATION_SELECT",
  SET_FAILED = "STATION_SET_FAILED",
  SET_READY = "STATION_SET_READY",
}
