export enum FormatsActionType {
  SAVE = "FORMAT_SAVE",
  SELECT = "FORMAT_SELECT",
  RESTORE = "FORMAT_RESTORE",
}

export enum StationsActionType {
  STORE = "STATION_STORE",
  SELECT = "STATION_SELECT",
  SET_FAILED = "STATION_SET_FAILED",
  SET_READY = "STATION_SET_READY",
}
