---
name: Build Tag with Artifacts

concurrency:
  group: build-tag

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      uploadToTag:
        type: string
        required: true
        description: "Upload built Bundle to Github tag"

jobs:
  build:
    uses: LinkedMink/.github/.github/workflows/build-npm-package.yml@main
    with:
      uploadBuild: true
  upload:
    needs: build
    uses: LinkedMink/.github/.github/workflows/publish-artifacts-for-tag.yml@main
    with:
      uploadToTag: ${{ github.event.inputs.uploadToTag || github.ref_name }}
      uploadedBuildName: ${{ needs.build.outputs.uploadedBuildName }}
    secrets:
      REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
