name: Build
on:
  workflow_call:
    inputs:
      uploadBuild:
        type: boolean
        required: false
        default: false
        description: 'Upload distribution files to Github'
    outputs:
      uploadedBuildName:
        description: "If a build is uploaded, this name will be output"
        value: ${{ jobs.build.outputs.uploadedBuildName }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      uploadedBuildName: ${{ steps.package-artifacts.outputs.uploadedBuildName }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'
    - name: Install
      run: yarn install --immutable
    - name: Lint
      run: yarn lint
    - name: Test
      run: yarn test || true
    - name: Build
      run: yarn build
    - id: package-artifacts
      name: Package Artifacts
      if: inputs.uploadBuild
      run: |
        echo '::echo::on'
        echo "PACKAGE_FILE=$(npm pack | tail -1)" >> $GITHUB_ENV
        echo "::set-output name=uploadedBuildName::$PACKAGE_FILE"
    - name: Upload Artifacts
      if: inputs.uploadBuild
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PACKAGE_FILE }}
        path: ${{ env.PACKAGE_FILE }}
