name: Build
on:
  workflow_call:
    inputs:
      uploadBuild:
        description: 'Upload distribution files to Github'
        default: false
        type: boolean
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'
    - name: Install
      run: yarn install
    - name: Lint
      run: yarn lint
    - name: Test
      run: yarn test || true
    - name: Build
      run: yarn build
    - name: Upload Packages
      if: ${{ inputs.uploadBuild }}
      uses: actions/upload-artifact@v2
      with:
        name: app-bundle
        path: build
