---
name: Build main Branch

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  build:
    uses: LinkedMink/.github/.github/workflows/build-npm-package.yml@main
    with:
      uploadBuild: false
