name: Build ref
concurrency: 
  group: build-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  pull_request:
    branches:
    - main

jobs:
  build:
    uses: LinkedMink/road-wave-fm-web/.github/workflows/build.yml@main
    with:
      uploadBuild: false
