---
name: Build Tag with Artifacts on Push

concurrency:
  group: build-tag

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    uses: LinkedMink/.github/.github/workflows/build-npm-package.yml@main
    with:
      uploadBuild: true
  upload:
    needs: build
    uses: LinkedMink/.github/.github/workflows/publish-artifacts-for-tag.yml@main
    with:
      uploadToTag: ${{ github.ref_name }}
      uploadedBuildName: ${{ needs.build.outputs.uploadedBuildName }}
    secrets:
      REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
