---
name: Build Other Branches

# yamllint disable-line rule:truthy
on:
  push:
    branches-ignore:
      - main
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build:
    uses: LinkedMink/.github/.github/workflows/build-npm-package.yml@main
    with:
      upload-build: false
      # node-js-version: "22"
