name: Develop
on:
  push:
    branches:
      - main
      - feature/*
      - hotfix/*
  pull_request:
    branches:
      - main
      - feature/*
      - hotfix/*
jobs:
  verify:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'
    - run: yarn install
    - run: yarn lint
    - run: yarn test
    - run: yarn build
