name: Verify Ref
concurrency: 
  group: build-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
    - main
    - develop
    - feature/*
    - fix/*
  workflow_dispatch:
    inputs:
      uploadBuild:
        description: 'Upload distribution files to Github'
        default: false
        type: boolean
jobs:
  build:
    uses: LinkedMink/road-wave-fm-web/.github/workflows/build.yml@main
    with:
      uploadBuild: ${{ github.event.inputs.uploadBuild }}
