name: Verify and Build
concurrency: 
  group: build-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_call:
    inputs:
      uploadBuild:
        description: 'Upload distribution files to Github'
        default: false
        type: boolean
  workflow_dispatch:
    inputs:
      uploadBuild:
        description: 'Upload distribution files to Github'
        default: false
        type: boolean
  push:
    branches:
    - main
    - develop
    - feature/*
    - fix/*
jobs:
  verify:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'
    - name: Install
      run: yarn install
    - name: Lint
      run: yarn lint
    - name: Test
      run: yarn test || true
    - name: Build
      run: yarn build
    - name: Upload Packages
      if: ${{ inputs.uploadBuild || github.event.inputs.uploadBuild }}
      uses: actions/upload-artifact@v2
      with:
        name: app-bundle
        path: build
